#!/usr/bin/env python
#Created by Sem Voigtländer
#Purpose: Parsing MACH-O executables and outputting their structure and symbols
#Description: machoparse is a wrapper around lief
import lief
import argparse
import os
parser = argparse.ArgumentParser(description='Dump mach-o symbols.')
parser.add_argument('binary', metavar='B', type=str, help='path to binary file to be parsed')
args = parser.parse_args()
try:
	binary = lief.parse(args.binary)
except Exception:
	print("Not a MACH-O binary")
	exit(-1)
print(binary)
